version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootsenha
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: ./backend
    container_name: nest-app-container
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: usuario
      DATABASE_PASSWORD: senha
      DATABASE_NAME: meu_banco
    command: npm run start:dev

volumes:
  mysql-data:
