services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: privus123
      MYSQL_DATABASE: azzo-database
      MYSQL_USER: azzo-user
      MYSQL_PASSWORD: privus123
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: nest-app-container
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: azzo-user
      DATABASE_PASSWORD: privus123
      DATABASE_NAME: azzo-database
    command: npm run start:dev
    working_dir: /usr/src/app
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    external: true 