services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: privus123
      MYSQL_DATABASE: azzo-database
      MYSQL_USER: azzo-user
      MYSQL_PASSWORD: privus123
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: nest-app-container
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: azzo-user
      DB_PASSWORD: privus123
      DB_NAME: azzo-database
      TZ: America/Sao_Paulo
    command: npm run start:dev
    working_dir: /usr/src/app
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    external: true

